# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PlacaView
                                 A QGIS plugin
 This plugin manages road signs
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-26
        copyright            : (C) 2024 by Tiago Barufi
        email                : barufi@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
from .placa_view import PlacaView

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PlacaView class from file PlacaView.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    #from .placa_view import PlacaView
    return PlacaView(iface)
